#!/usr/bin/env python3
"""Supplementary China bird species data for build_china_birds_v2.py"""

PROTECTION_MAP = {
    "Grus japonensis":"I","Grus leucogeranus":"I","Grus nigricollis":"I",
    "Nipponia nippon":"I","Ciconia boyciana":"I","Pavo muticus":"I",
    "Lophophorus lhuysii":"I","Lophophorus sclateri":"I","Lophophorus impejanus":"I",
    "Tragopan caboti":"I","Tragopan blythii":"I","Crossoptilon mantchuricum":"I",
    "Syrmaticus ellioti":"I","Syrmaticus humiae":"I","Syrmaticus mikado":"I",
    "Lophura swinhoii":"I","Arborophila rufipectus":"I","Arborophila ardens":"I",
    "Tetrastes sewerzowi":"I","Tetrao urogalloides":"I","Polyplectron bicalcaratum":"I",
    "Aquila chrysaetos":"I","Haliaeetus albicilla":"I","Aegypius monachus":"I",
    "Gypaetus barbatus":"I","Gyps himalayensis":"I","Pelecanus crispus":"I",
    "Gorsachius magnificus":"I","Mycteria leucocephala":"I","Platalea minor":"I",
    "Buceros bicornis":"I","Indicator xanthonotus":"I","Pitta nympha":"I",
    "Otis tarda":"I","Tetrax tetrax":"I","Grus monacha":"I","Grus vipio":"I",
    "Anthropoides virgo":"I","Thalasseus bernsteini":"I","Mergus squamatus":"I",
    "Aythya baeri":"I","Larus relictus":"I","Egretta eulophotes":"I",
    "Tetraogallus tibetanus":"II","Tetraogallus himalayensis":"II",
    "Tetraophasis obscurus":"II","Tetraophasis szechenyii":"II",
    "Alectoris magna":"II","Arborophila gingica":"II","Arborophila crudigularis":"II",
    "Tragopan temminckii":"II","Ithaginis cruentus":"II","Gallus gallus":"II",
    "Lophura nycthemera":"II","Crossoptilon crossoptilon":"II",
    "Crossoptilon auritum":"II","Syrmaticus reevesii":"II",
    "Chrysolophus pictus":"II","Chrysolophus amherstiae":"II",
    "Pucrasia macrolopha":"II","Tetrastes bonasia":"II","Lyrurus tetrix":"II",
    "Pandion haliaetus":"II","Accipiter nisus":"II","Accipiter virgatus":"II",
    "Accipiter gentilis":"II","Accipiter soloensis":"II","Buteo japonicus":"II",
    "Buteo lagopus":"II","Buteo hemilasius":"II","Milvus migrans":"II",
    "Circus cyaneus":"II","Circus melanoleucos":"II","Elanus caeruleus":"II",
    "Pernis ptilorhynchus":"II","Spilornis cheela":"II",
    "Falco peregrinus":"II","Falco subbuteo":"II","Falco tinnunculus":"II",
    "Falco columbarius":"II","Falco amurensis":"II","Falco cherrug":"II",
    "Bubo bubo":"II","Bubo scandiacus":"II","Strix aluco":"II",
    "Strix leptogrammica":"II","Strix uralensis":"II","Asio otus":"II",
    "Asio flammeus":"II","Otus lettia":"II","Otus sunia":"II",
    "Otus spilocephalus":"II","Glaucidium cuculoides":"II",
    "Glaucidium brodiei":"II","Athene noctua":"II","Ninox scutulata":"II",
    "Tyto longimembris":"II","Tyto alba":"II","Ketupa zeylonensis":"II",
    "Aix galericulata":"II","Cygnus columbianus":"II","Cygnus cygnus":"II",
    "Anser indicus":"II","Grus grus":"II","Alcedo atthis":"II",
    "Upupa epops":"II","Psittacula alexandri":"II","Psittacula derbiana":"II",
    "Ibidorhyncha struthersii":"II","Recurvirostra avosetta":"II",
    "Podiceps cristatus":"II","Nisaetus nipalensis":"II",
    "Haliaeetus pelagicus":"II","Haliaeetus leucoryphus":"II",
    "Ciconia nigra":"II","Phalacrocorax pelagicus":"II",
    "Strix nebulosa":"II","Aegolius funereus":"II",
}

CHINESE_NAMES_MAP = {}

# (scientific_name, chinese_name) — ALL China bird species
# Species already in eBird zh set will be deduplicated by the build script
SUPP_SPECIES = [
# ── Galliformes 鸡形目 ──
("Lerwa lerwa","雪鹑"),("Tetraophasis obscurus","暗腹雪鸡"),
("Tetraophasis szechenyii","黄喉雪鸡"),("Tetraogallus tibetanus","藏雪鸡"),
("Tetraogallus himalayensis","喜马拉雅雪鸡"),("Tetraogallus altaicus","阿尔泰雪鸡"),
("Alectoris chukar","石鸡"),("Alectoris magna","大石鸡"),
("Francolinus pintadeanus","中华鹧鸪"),("Perdix dauurica","斑翅山鹑"),
("Perdix hodgsoniae","高原山鹑"),("Coturnix japonica","鹌鹑"),
("Synoicus chinensis","蓝胸鹑"),("Arborophila torqueola","环颈山鹧鸪"),
("Arborophila rufipectus","四川山鹧鸪"),("Arborophila mandellii","红胸山鹧鸪"),
("Arborophila gingica","白眉山鹧鸪"),("Arborophila ardens","海南山鹧鸪"),
("Arborophila brunneopectus","褐胸山鹧鸪"),("Arborophila rufogularis","红喉山鹧鸪"),
("Arborophila crudigularis","台湾山鹧鸪"),("Arborophila charltonii","绿脚山鹧鸪"),
("Bambusicola thoracicus","灰胸竹鸡"),("Bambusicola fytchii","棕胸竹鸡"),
("Tragopan temminckii","红腹角雉"),("Tragopan blythii","灰腹角雉"),
("Tragopan caboti","黄腹角雉"),("Tragopan satyra","红胸角雉"),
("Ithaginis cruentus","血雉"),("Lophophorus impejanus","棕尾虹雉"),
("Lophophorus sclateri","白尾梢虹雉"),("Lophophorus lhuysii","绿尾虹雉"),
("Gallus gallus","红原鸡"),("Polyplectron bicalcaratum","灰孔雀雉"),
("Lophura nycthemera","白鹇"),("Lophura swinhoii","蓝鹇"),
("Crossoptilon crossoptilon","白马鸡"),("Crossoptilon mantchuricum","褐马鸡"),
("Crossoptilon auritum","蓝马鸡"),("Syrmaticus reevesii","白冠长尾雉"),
("Syrmaticus ellioti","白颈长尾雉"),("Syrmaticus humiae","黑颈长尾雉"),
("Syrmaticus mikado","黑长尾雉"),("Chrysolophus pictus","红腹锦鸡"),
("Chrysolophus amherstiae","白腹锦鸡"),("Phasianus colchicus","雉鸡"),
("Pucrasia macrolopha","勺鸡"),("Tetrastes sewerzowi","斑尾榛鸡"),
("Tetrastes bonasia","花尾榛鸡"),("Lyrurus tetrix","黑琴鸡"),
("Tetrao urogalloides","细嘴松鸡"),("Pavo muticus","绿孔雀"),
("Bonasa sewerzowi","斑尾榛鸡"),
# ── Anseriformes 雁形目 ──
("Dendrocygna javanica","栗树鸭"),("Oxyura leucocephala","白头硬尾鸭"),
("Cygnus olor","疣鼻天鹅"),("Cygnus cygnus","大天鹅"),
("Cygnus columbianus","小天鹅"),("Anser cygnoid","鸿雁"),
("Anser fabalis","豆雁"),("Anser serrirostris","短嘴豆雁"),
("Anser albifrons","白额雁"),("Anser erythropus","小白额雁"),
("Anser anser","灰雁"),("Anser indicus","斑头雁"),
("Anser caerulescens","雪雁"),("Branta bernicla","黑雁"),
("Tadorna ferruginea","赤麻鸭"),("Tadorna tadorna","翘鼻麻鸭"),
("Aix galericulata","鸳鸯"),("Sibirionetta formosa","花脸鸭"),
("Mareca strepera","赤膀鸭"),("Mareca falcata","罗纹鸭"),
("Mareca penelope","赤颈鸭"),("Spatula querquedula","白眉鸭"),
("Spatula clypeata","琵嘴鸭"),("Anas zonorhyncha","斑嘴鸭"),
("Anas platyrhynchos","绿头鸭"),("Anas crecca","绿翅鸭"),
("Anas acuta","针尾鸭"),("Netta rufina","赤嘴潜鸭"),
("Aythya ferina","红头潜鸭"),("Aythya nyroca","白眼潜鸭"),
("Aythya baeri","青头潜鸭"),("Aythya fuligula","凤头潜鸭"),
("Aythya marila","斑背潜鸭"),("Clangula hyemalis","长尾鸭"),
("Melanitta stejnegeri","斑脸海番鸭"),("Bucephala clangula","鹊鸭"),
("Mergellus albellus","白秋沙鸭"),("Mergus squamatus","中华秋沙鸭"),
("Mergus serrator","红胸秋沙鸭"),("Mergus merganser","普通秋沙鸭"),
("Histrionicus histrionicus","丑鸭"),("Somateria mollissima","绒鸭"),
# ── Podicipediformes 鸊鷉目 ──
("Tachybaptus ruficollis","小鸊鷉"),("Podiceps cristatus","凤头鸊鷉"),
("Podiceps grisegena","赤颈鸊鷉"),("Podiceps auritus","角鸊鷉"),
("Podiceps nigricollis","黑颈鸊鷉"),
# ── Phoenicopteriformes 火烈鸟目 ──
("Phoenicopterus roseus","大红鹳"),
# ── Columbiformes 鸽形目 ──
("Columba livia","原鸽"),("Columba rupestris","岩鸽"),
("Columba hodgsonii","斑林鸽"),("Columba leuconota","雪鸽"),
("Columba pulchricollis","灰林鸽"),("Columba punicea","紫林鸽"),
("Streptopelia orientalis","山斑鸠"),("Streptopelia tranquebarica","火斑鸠"),
("Streptopelia decaocto","灰斑鸠"),("Spilopelia chinensis","珠颈斑鸠"),
("Macropygia unchall","棕头鹃鸠"),("Chalcophaps indica","绿翅金鸠"),
("Treron sieboldii","红翅绿鸠"),("Treron sphenurus","楔尾绿鸠"),
("Treron apicauda","针尾绿鸠"),("Treron phoenicopterus","黄脚绿鸠"),
("Treron bicincta","橙胸绿鸠"),("Treron curvirostra","厚嘴绿鸠"),
("Ptilinopus leclancheri","黑颏果鸠"),("Ducula aenea","绿皇鸠"),
("Ducula badia","山皇鸠"),
# ── Pterocliformes 沙鸡目 ──
("Syrrhaptes paradoxus","毛腿沙鸡"),("Syrrhaptes tibetanus","西藏毛腿沙鸡"),
("Pterocles orientalis","黑腹沙鸡"),
# ── Otidiformes 鸨目 ──
("Otis tarda","大鸨"),("Tetrax tetrax","小鸨"),
("Chlamydotis macqueenii","波斑鸨"),
# ── Cuculiformes 鹃形目 ──
("Centropus sinensis","褐翅鸦鹃"),("Centropus bengalensis","小鸦鹃"),
("Phaenicophaeus tristis","绿嘴地鹃"),("Eudynamys scolopaceus","噪鹃"),
("Clamator coromandus","红翅凤头鹃"),("Surniculus lugubris","乌鹃"),
("Hierococcyx sparverioides","大鹰鹃"),("Hierococcyx nisicolor","棕腹鹰鹃"),
("Hierococcyx hyperythrus","北鹰鹃"),("Cuculus canorus","大杜鹃"),
("Cuculus micropterus","四声杜鹃"),("Cuculus saturatus","中杜鹃"),
("Cuculus optatus","北方中杜鹃"),("Cuculus poliocephalus","小杜鹃"),
("Cacomantis merulinus","八声杜鹃"),("Cacomantis sonneratii","灰腹杜鹃"),
# ── Caprimulgiformes 夜鹰目 ──
("Caprimulgus jotaka","普通夜鹰"),("Caprimulgus affinis","林夜鹰"),
("Caprimulgus macrurus","长尾夜鹰"),("Caprimulgus europaeus","欧夜鹰"),
("Caprimulgus indicus","中亚夜鹰"),("Lyncornis macrotis","大耳夜鹰"),
# ── Apodiformes 雨燕目 ──
("Aerodramus brevirostris","短嘴金丝燕"),("Aerodramus fuciphagus","爪哇金丝燕"),
("Hirundapus caudacutus","白喉针尾雨燕"),("Hirundapus cochinchinensis","灰喉针尾雨燕"),
("Apus apus","普通雨燕"),("Apus pacificus","白腰雨燕"),
("Apus nipalensis","小白腰雨燕"),("Cypsiurus balasiensis","棕雨燕"),
("Hemiprocne coronata","凤头树燕"),
# ── Gruiformes 鹤形目 ──
("Grus japonensis","丹顶鹤"),("Grus leucogeranus","白鹤"),
("Grus monacha","白头鹤"),("Grus grus","灰鹤"),
("Grus nigricollis","黑颈鹤"),("Grus vipio","白枕鹤"),
("Anthropoides virgo","蓑羽鹤"),("Rallus indicus","普通秧鸡"),
("Lewinia striata","蓝胸秧鸡"),("Gallirallus striatus","纹胸秧鸡"),
("Zapornia pusilla","小田鸡"),("Zapornia fusca","红腿斑秧鸡"),
("Zapornia paykullii","斑胸田鸡"),("Zapornia akool","棕背田鸡"),
("Amaurornis phoenicurus","白胸苦恶鸟"),("Gallinula chloropus","黑水鸡"),
("Fulica atra","白骨顶"),("Gallicrex cinerea","董鸡"),
("Porphyrio poliocephalus","灰头紫水鸡"),("Crex crex","长脚秧鸡"),
# ── Charadriiformes 鸻形目 ──
("Burhinus oedicnemus","石鸻"),("Esacus recurvirostris","大石鸻"),
("Haematopus ostralegus","蛎鹬"),("Ibidorhyncha struthersii","鹮嘴鹬"),
("Himantopus himantopus","黑翅长脚鹬"),("Recurvirostra avosetta","反嘴鹬"),
("Vanellus vanellus","凤头麦鸡"),("Vanellus cinereus","灰头麦鸡"),
("Vanellus indicus","肉垂麦鸡"),("Pluvialis squatarola","灰斑鸻"),
("Pluvialis fulva","金斑鸻"),("Charadrius hiaticula","剑鸻"),
("Charadrius dubius","金眶鸻"),("Charadrius placidus","长嘴剑鸻"),
("Charadrius alexandrinus","环颈鸻"),("Charadrius mongolus","蒙古沙鸻"),
("Charadrius leschenaultii","铁嘴沙鸻"),("Charadrius veredus","东方鸻"),
("Charadrius morinellus","小嘴鸻"),("Scolopax rusticola","丘鹬"),
("Gallinago gallinago","扇尾沙锥"),("Gallinago megala","大沙锥"),
("Gallinago stenura","针尾沙锥"),("Gallinago hardwickii","澳南沙锥"),
("Gallinago solitaria","孤沙锥"),("Limosa limosa","黑尾塍鹬"),
("Limosa lapponica","斑尾塍鹬"),("Numenius arquata","白腰杓鹬"),
("Numenius phaeopus","中杓鹬"),("Numenius minutus","小杓鹬"),
("Numenius madagascariensis","大杓鹬"),("Tringa totanus","红脚鹬"),
("Tringa erythropus","鹤鹬"),("Tringa nebularia","青脚鹬"),
("Tringa stagnatilis","泽鹬"),("Tringa glareola","林鹬"),
("Tringa ochropus","白腰草鹬"),("Tringa brevipes","灰尾漂鹬"),
("Xenus cinereus","翘嘴鹬"),("Actitis hypoleucos","矶鹬"),
("Phalaropus lobatus","红颈瓣蹼鹬"),("Phalaropus fulicarius","灰瓣蹼鹬"),
("Arenaria interpres","翻石鹬"),("Calidris tenuirostris","大滨鹬"),
("Calidris canutus","红腹滨鹬"),("Calidris pugnax","流苏鹬"),
("Calidris falcinellus","弯嘴滨鹬"),("Calidris ferruginea","弯嘴滨鹬"),
("Calidris temminckii","青脚滨鹬"),("Calidris subminuta","长趾滨鹬"),
("Calidris ruficollis","红颈滨鹬"),("Calidris alba","三趾滨鹬"),
("Calidris alpina","黑腹滨鹬"),("Calidris acuminata","尖尾滨鹬"),
("Limnodromus scolopaceus","长嘴半蹼鹬"),("Limnodromus semipalmatus","半蹼鹬"),
("Turnix suscitator","棕三趾鹑"),("Turnix tanki","林三趾鹑"),
("Glareola maldivarum","普通燕鸻"),
("Chroicocephalus ridibundus","红嘴鸥"),("Chroicocephalus saundersi","黑嘴鸥"),
("Chroicocephalus brunnicephalus","棕头鸥"),("Larus crassirostris","黑尾鸥"),
("Larus vegae","织女银鸥"),("Larus schistisagus","灰背鸥"),
("Larus ichthyaetus","渔鸥"),("Larus relictus","遗鸥"),
("Larus canus","海鸥"),("Rissa tridactyla","三趾鸥"),
("Gelochelidon nilotica","鸥嘴噪鸥"),("Hydroprogne caspia","红嘴巨鸥"),
("Thalasseus bergii","大凤头燕鸥"),("Thalasseus bernsteini","中华凤头燕鸥"),
("Sternula albifrons","白额燕鸥"),("Onychoprion fuscatus","乌燕鸥"),
("Onychoprion anaethetus","褐翅燕鸥"),("Sterna hirundo","普通燕鸥"),
("Sterna dougallii","粉红燕鸥"),("Sterna sumatrana","黑枕燕鸥"),
("Chlidonias hybrida","须浮鸥"),("Chlidonias leucopterus","白翅浮鸥"),
("Anous stolidus","白顶玄燕鸥"),
("Stercorarius parasiticus","短尾贼鸥"),("Stercorarius pomarinus","中贼鸥"),
("Stercorarius longicaudus","长尾贼鸥"),
("Uria aalge","崖海鸦"),("Cerorhinca monocerata","角嘴海雀"),
("Synthliboramphus antiquus","冠海雀"),
# ── Gaviiformes 潜鸟目 ──
("Gavia stellata","红喉潜鸟"),("Gavia arctica","黑喉潜鸟"),
("Gavia pacifica","太平洋潜鸟"),("Gavia adamsii","白嘴潜鸟"),
# ── Procellariiformes 鹱形目 ──
("Phoebastria albatrus","短尾信天翁"),("Phoebastria immutabilis","黑脚信天翁"),
("Phoebastria nigripes","黑脚信天翁"),("Fulmarus glacialis","暴风鹱"),
("Calonectris leucomelas","白额鹱"),("Ardenna pacifica","楔尾鹱"),
("Ardenna grisea","灰鹱"),("Ardenna tenuirostris","短尾鹱"),
("Pterodroma hypoleuca","白腹圆尾鹱"),
("Hydrobates monorhis","黑叉尾海燕"),("Hydrobates leucorhous","白腰叉尾海燕"),
# ── Phaethontiformes 鹲目 ──
("Phaethon rubricauda","红尾鹲"),("Phaethon lepturus","白尾鹲"),
# ── Ciconiiformes 鹳形目 ──
("Ciconia boyciana","东方白鹳"),("Ciconia nigra","黑鹳"),
("Ciconia ciconia","白鹳"),("Mycteria leucocephala","白头鹮鹳"),
("Ephippiorhynchus asiaticus","黑颈鹳"),
# ── Suliformes 鲣鸟目 ──
("Fregata minor","白斑军舰鸟"),("Fregata ariel","白腹军舰鸟"),
("Sula dactylatra","蓝脸鲣鸟"),("Sula leucogaster","褐鲣鸟"),
("Sula sula","红脚鲣鸟"),("Anhinga melanogaster","蛇鹈"),
("Phalacrocorax carbo","普通鸬鹚"),("Microcarbo niger","黑颈鸬鹚"),
("Phalacrocorax capillatus","暗绿背鸬鹚"),("Phalacrocorax pelagicus","海鸬鹚"),
# ── Pelecaniformes 鹈形目 ──
("Pelecanus crispus","卷羽鹈鹕"),("Pelecanus philippensis","斑嘴鹈鹕"),
("Pelecanus onocrotalus","白鹈鹕"),
("Botaurus stellaris","大麻鳽"),("Ixobrychus sinensis","黄苇鳽"),
("Ixobrychus eurhythmus","紫背苇鳽"),("Ixobrychus cinnamomeus","栗苇鳽"),
("Ixobrychus flavicollis","黑苇鳽"),("Gorsachius magnificus","海南鳽"),
("Gorsachius melanolophus","黑冠鳽"),("Nycticorax nycticorax","夜鹭"),
("Ardeola bacchus","池鹭"),("Butorides striata","绿鹭"),
("Bubulcus ibis","牛背鹭"),("Ardea cinerea","苍鹭"),
("Ardea alba","大白鹭"),("Ardea intermedia","中白鹭"),
("Egretta garzetta","白鹭"),("Egretta eulophotes","黄嘴白鹭"),
("Egretta sacra","岩鹭"),("Ardea purpurea","草鹭"),
("Threskiornis melanocephalus","黑头白鹮"),("Nipponia nippon","朱鹮"),
("Platalea leucorodia","白琵鹭"),("Platalea minor","黑脸琵鹭"),
("Plegadis falcinellus","彩鹮"),
# ── Accipitriformes 鹰形目 ──
("Pandion haliaetus","鹗"),("Elanus caeruleus","黑翅鸢"),
("Pernis ptilorhynchus","凤头蜂鹰"),("Gypaetus barbatus","胡兀鹫"),
("Gyps himalayensis","高山兀鹫"),("Aegypius monachus","秃鹫"),
("Spilornis cheela","蛇雕"),("Circaetus gallicus","短趾雕"),
("Nisaetus nipalensis","鹰雕"),("Ictinaetus malaiensis","黑冠鹃隼"),
("Aquila chrysaetos","金雕"),("Aquila heliaca","白肩雕"),
("Aquila nipalensis","草原雕"),("Clanga clanga","乌雕"),
("Aquila fasciata","白腹隼雕"),("Hieraaetus pennatus","靴隼雕"),
("Circus aeruginosus","白头鹞"),("Circus spilonotus","白腹鹞"),
("Circus cyaneus","白尾鹞"),("Circus macrourus","草原鹞"),
("Circus melanoleucos","鹊鹞"),("Accipiter nisus","雀鹰"),
("Accipiter virgatus","松雀鹰"),("Accipiter soloensis","赤腹鹰"),
("Accipiter gentilis","苍鹰"),("Accipiter badius","褐耳鹰"),
("Accipiter gularis","日本松雀鹰"),("Milvus migrans","黑鸢"),
("Haliastur indus","栗鸢"),("Haliaeetus albicilla","白尾海雕"),
("Haliaeetus leucoryphus","玉带海雕"),("Haliaeetus pelagicus","虎头海雕"),
("Butastur indicus","灰脸鵟鹰"),("Buteo japonicus","普通鵟"),
("Buteo lagopus","毛脚鵟"),("Buteo hemilasius","大鵟"),
("Buteo buteo","欧亚鵟"),("Buteo rufinus","棕尾鵟"),
# ── Strigiformes 鸮形目 ──
("Tyto longimembris","草鸮"),("Tyto alba","仓鸮"),
("Otus lettia","领角鸮"),("Otus sunia","红角鸮"),
("Otus spilocephalus","黄嘴角鸮"),("Otus elegans","琉球角鸮"),
("Otus scops","欧亚角鸮"),("Otus brucei","纵纹角鸮"),
("Bubo bubo","雕鸮"),("Bubo scandiacus","雪鸮"),
("Bubo coromandus","黄脚渔鸮"),("Ketupa zeylonensis","褐渔鸮"),
("Ketupa flavipes","黄脚鱼鸮"),("Glaucidium cuculoides","斑头鸺鹠"),
("Glaucidium brodiei","领鸺鹠"),("Athene noctua","纵纹腹小鸮"),
("Strix aluco","灰林鸮"),("Strix nivicolum","东方灰林鸮"),
("Strix leptogrammica","褐林鸮"),("Strix uralensis","长尾林鸮"),
("Strix nebulosa","乌林鸮"),("Asio otus","长耳鸮"),
("Asio flammeus","短耳鸮"),("Ninox scutulata","鹰鸮"),
("Ninox japonica","北鹰鸮"),("Aegolius funereus","鬼鸮"),
# ── Bucerotiformes 犀鸟目 ──
("Buceros bicornis","双角犀鸟"),("Anthracoceros albirostris","冠斑犀鸟"),
("Anorrhinus galeritus","棕颈犀鸟"),("Rhyticeros undulatus","皱盔犀鸟"),
("Upupa epops","戴胜"),
# ── Trogoniformes 咬鹃目 ──
("Harpactes erythrocephalus","红头咬鹃"),("Harpactes wardi","红腹咬鹃"),
("Harpactes oreskios","橙胸咬鹃"),
# ── Coraciiformes 佛法僧目 ──
("Eurystomus orientalis","三宝鸟"),("Coracias benghalensis","棕胸佛法僧"),
("Alcedo atthis","普通翠鸟"),("Alcedo hercules","斑头大翠鸟"),
("Ceyx erithaca","三趾翠鸟"),("Halcyon smyrnensis","白胸翡翠"),
("Halcyon pileata","蓝翡翠"),("Todiramphus chloris","白领翡翠"),
("Megaceryle lugubris","冠鱼狗"),("Ceryle rudis","斑鱼狗"),
("Merops viridis","蓝喉蜂虎"),("Merops philippinus","栗喉蜂虎"),
("Merops orientalis","绿喉蜂虎"),("Merops leschenaulti","栗头蜂虎"),
("Nyctyornis athertoni","蓝须夜蜂虎"),
# ── Piciformes 鴷形目 ──
("Indicator xanthonotus","黄腰响蜜鴷"),
("Psilopogon virens","大拟啄木鸟"),("Psilopogon franklinii","金喉拟啄木鸟"),
("Psilopogon asiaticus","蓝喉拟啄木鸟"),("Psilopogon faiostrictus","绿拟啄木鸟"),
("Psilopogon lineatus","斑头绿拟啄木鸟"),("Psilopogon nuchalis","台湾拟啄木鸟"),
("Jynx torquilla","蚁鴷"),("Picus canus","灰头绿啄木鸟"),
("Picus viridanus","鳞腹绿啄木鸟"),("Picus vittatus","纹胸绿啄木鸟"),
("Picus rabieri","红领绿啄木鸟"),("Picus squamatus","鳞喉绿啄木鸟"),
("Chrysophlegma flavinucha","大黄冠啄木鸟"),("Gecinulus grantia","竹啄木鸟"),
("Dryocopus javensis","白腹黑啄木鸟"),("Dryocopus martius","黑啄木鸟"),
("Dendrocopos major","大斑啄木鸟"),("Dendrocopos canicapillus","星头啄木鸟"),
("Dendrocopos hyperythrus","棕腹啄木鸟"),("Dendrocopos atratus","纹胸啄木鸟"),
("Dendrocopos darjellensis","黄颈啄木鸟"),("Dendrocopos cathpharius","赤胸啄木鸟"),
("Leuconotopicus leucotos","白背啄木鸟"),("Yungipicus kizuki","小星头啄木鸟"),
("Picoides tridactylus","三趾啄木鸟"),("Dendrocopos macei","纹背啄木鸟"),
("Dinopium javanense","金背三趾啄木鸟"),("Chrysocolaptes lucidus","大金背啄木鸟"),
("Blythipicus pyrrhotis","黄嘴栗啄木鸟"),("Mulleripicus pulverulentus","大灰啄木鸟"),
("Sasia ochracea","白眉棕啄木鸟"),
# ── Falconiformes 隼形目 ──
("Falco tinnunculus","红隼"),("Falco naumanni","黄爪隼"),
("Falco amurensis","阿穆尔隼"),("Falco columbarius","灰背隼"),
("Falco subbuteo","燕隼"),("Falco severus","猛隼"),
("Falco cherrug","猎隼"),("Falco rusticolus","矛隼"),
("Falco peregrinus","游隼"),("Microhierax melanoleucos","白腿小隼"),
("Microhierax caerulescens","红腿小隼"),
# ── Psittaciformes 鹦鹉目 ──
("Psittacula alexandri","绯胸鹦鹉"),("Psittacula derbiana","大紫胸鹦鹉"),
("Psittacula eupatria","亚历山大鹦鹉"),("Psittacula krameri","红领绿鹦鹉"),
("Psittacula himalayana","灰头鹦鹉"),("Loriculus vernalis","短尾鹦鹉"),
# ── Passeriformes 雀形目 ──
# Pittidae 八色鸫科
("Pitta nympha","仙八色鸫"),("Pitta moluccensis","蓝翅八色鸫"),
("Pitta sordida","绿胸八色鸫"),("Hydrornis nipalensis","蓝枕八色鸫"),
("Hydrornis phayrei","栗头八色鸫"),("Hydrornis cyaneus","蓝八色鸫"),
("Erythropitta erythrogaster","红腹八色鸫"),("Pitta megarhyncha","大嘴八色鸫"),
# Eurylaimidae 阔嘴鸟科
("Psarisomus dalhousiae","长尾阔嘴鸟"),("Serilophus lunatus","银胸丝冠鸟"),
# Campephagidae 山椒鸟科
("Pericrocotus divaricatus","灰山椒鸟"),("Pericrocotus roseus","粉红山椒鸟"),
("Pericrocotus cantonensis","小灰山椒鸟"),("Pericrocotus solaris","灰喉山椒鸟"),
("Pericrocotus ethologus","长尾山椒鸟"),("Pericrocotus brevirostris","短嘴山椒鸟"),
("Pericrocotus speciosus","赤红山椒鸟"),("Pericrocotus flammeus","橙色山椒鸟"),
("Lalage melaschistos","暗灰鹃鵙"),("Coracina macei","大鹃鵙"),
("Coracina melaschistos","暗灰鹃鵙"),
# Oriolidae 黄鹂科
("Oriolus chinensis","黑枕黄鹂"),("Oriolus traillii","朱鹂"),
("Oriolus mellianus","鹊色鹂"),("Oriolus xanthornus","黑头黄鹂"),
# Artamidae 燕鵙科
("Artamus fuscus","灰燕鵙"),
# Aegithinidae 雀鹎科
("Aegithina tiphia","黑翅雀鹎"),
# Laniidae 伯劳科
("Lanius tigrinus","虎纹伯劳"),("Lanius bucephalus","牛头伯劳"),
("Lanius cristatus","红尾伯劳"),("Lanius collurioides","棕背伯劳"),
("Lanius vittatus","长尾灰伯劳"),("Lanius schach","棕背伯劳"),
("Lanius tephronotus","灰背伯劳"),("Lanius sphenocercus","楔尾伯劳"),
("Lanius isabellinus","荒漠伯劳"),("Lanius excubitor","灰伯劳"),
("Lanius minor","黑额伯劳"),
# Corvidae 鸦科
("Garrulus glandarius","松鸦"),("Garrulus lidthi","琉球松鸦"),
("Urocissa erythroryncha","红嘴蓝鹊"),("Urocissa caerulea","台湾蓝鹊"),
("Cissa chinensis","蓝绿鹊"),("Cissa hypoleuca","黄胸绿鹊"),
("Cyanopica cyanus","灰喜鹊"),("Pica pica","喜鹊"),
("Pica bottanensis","黑尾喜鹊"),("Nucifraga caryocatactes","星鸦"),
("Pyrrhocorax pyrrhocorax","红嘴山鸦"),("Pyrrhocorax graculus","黄嘴山鸦"),
("Corvus monedula","寒鸦"),("Corvus dauuricus","达乌里寒鸦"),
("Corvus frugilegus","秃鼻乌鸦"),("Corvus corone","小嘴乌鸦"),
("Corvus macrorhynchos","大嘴乌鸦"),("Corvus corax","渡鸦"),
("Corvus torquatus","白颈鸦"),("Corvus splendens","家鸦"),
("Dendrocitta formosae","灰树鹊"),("Dendrocitta vagabunda","棕腹树鹊"),
("Temnurus temnurus","叉尾树鹊"),("Podoces hendersoni","黑尾地鸦"),
("Podoces biddulphi","白尾地鸦"),("Perisoreus infaustus","北噪鸦"),
("Pseudopodoces humilis","褐背拟地鸦"),
# Dicruridae 卷尾科
("Dicrurus macrocercus","黑卷尾"),("Dicrurus leucophaeus","灰卷尾"),
("Dicrurus annectens","鸦嘴卷尾"),("Dicrurus aeneus","古铜色卷尾"),
("Dicrurus remifer","小盘尾"),("Dicrurus hottentottus","发冠卷尾"),
("Dicrurus paradiseus","大盘尾"),
# Monarchidae 王鹟科
("Terpsiphone paradisi","寿带"),("Terpsiphone atrocaudata","紫寿带"),
("Terpsiphone incei","寿带"),
("Hypothymis azurea","黑枕王鹟"),
# Rhipiduridae 扇尾鹟科
("Rhipidura albicollis","白喉扇尾鹟"),("Rhipidura aureola","白眉扇尾鹟"),
# Stenostiridae 仙鹟科
("Culicicapa ceylonensis","方尾鹟"),
# Paridae 山雀科
("Parus major","大山雀"),("Parus minor","远东山雀"),
("Parus monticolus","绿背山雀"),("Machlolophus spilonotus","黄颊山雀"),
("Periparus ater","煤山雀"),("Periparus rubidiventris","棕腹山雀"),
("Periparus venustulus","黄腹山雀"),("Poecile palustris","沼泽山雀"),
("Poecile montanus","褐头山雀"),("Poecile superciliosus","白眉山雀"),
("Poecile davidi","褐冠山雀"),("Lophophanes dichrous","褐冠山雀"),
("Sittiparus varius","杂色山雀"),("Melanochlora sultanea","冠山雀"),
("Sylviparus modestus","黄眉林雀"),
# Remizidae 攀雀科
("Remiz pendulinus","攀雀"),("Remiz consobrinus","中华攀雀"),
# Alaudidae 百灵科
("Melanocorypha mongolica","蒙古百灵"),("Melanocorypha maxima","长嘴百灵"),
("Melanocorypha calandra","凤头百灵"),("Melanocorypha bimaculata","二斑百灵"),
("Calandrella brachydactyla","短趾百灵"),("Calandrella acutirostris","细嘴短趾百灵"),
("Alaudala cheleensis","亚洲短趾百灵"),("Galerida cristata","凤头百灵"),
("Eremophila alpestris","角百灵"),("Alauda gulgula","小云雀"),
("Alauda arvensis","云雀"),("Lullula arborea","林百灵"),
# Pycnonotidae 鹎科
("Spizixos canifrons","凤头雀嘴鹎"),("Spizixos semitorques","领雀嘴鹎"),
("Pycnonotus striatus","纹喉鹎"),("Pycnonotus jocosus","红耳鹎"),
("Pycnonotus xanthorrhous","黄臀鹎"),("Pycnonotus sinensis","白头鹎"),
("Pycnonotus taivanus","台湾鹎"),("Pycnonotus aurigaster","白喉红臀鹎"),
("Pycnonotus cafer","黑喉红臀鹎"),("Pycnonotus melanicterus","黑冠黄鹎"),
("Alophoixus pallidus","灰眼短脚鹎"),("Hemixos flavala","棕耳鹎"),
("Hemixos castanonotus","栗背短脚鹎"),("Hypsipetes leucocephalus","黑短脚鹎"),
("Hypsipetes mcclellandii","栗耳短脚鹎"),("Iole propinqua","灰眼鹎"),
("Ixos mcclellandii","棕耳鹎"),
# Hirundinidae 燕科
("Riparia riparia","崖沙燕"),("Riparia chinensis","淡色崖沙燕"),
("Hirundo rustica","家燕"),("Hirundo tahitica","洋斑燕"),
("Cecropis daurica","金腰燕"),("Cecropis striolata","斑腰燕"),
("Delichon urbicum","毛脚燕"),("Delichon dasypus","烟腹毛脚燕"),
("Ptyonoprogne rupestris","岩燕"),("Ptyonoprogne concolor","纯色岩燕"),
# Cettiidae 树莺科
("Cettia cetti","棕扇尾莺"),("Horornis diphone","日本树莺"),
("Horornis fortipes","强脚树莺"),("Horornis canturians","远东树莺"),
("Horornis acanthizoides","黄腹树莺"),("Horornis brunnifrons","棕脸鹟莺"),
("Abroscopus albogularis","棕头鹟莺"),("Abroscopus schisticeps","黑脸鹟莺"),
("Abroscopus superciliaris","凤头雀莺"),
# Aegithalidae 长尾山雀科
("Aegithalos caudatus","银喉长尾山雀"),("Aegithalos concinnus","红头长尾山雀"),
("Aegithalos leucogenys","白颊长尾山雀"),("Aegithalos fuliginosus","银脸长尾山雀"),
("Aegithalos iouschistos","黑眉长尾山雀"),
# Phylloscopidae 柳莺科
("Phylloscopus trochilus","柳莺"),("Phylloscopus fuscatus","褐柳莺"),
("Phylloscopus affinis","棕眉柳莺"),("Phylloscopus subaffinis","黄腹柳莺"),
("Phylloscopus griseolus","灰腹柳莺"),("Phylloscopus armandii","棕腹柳莺"),
("Phylloscopus schwarzi","巨嘴柳莺"),("Phylloscopus proregulus","黄腰柳莺"),
("Phylloscopus kansuensis","甘肃柳莺"),("Phylloscopus inornatus","黄眉柳莺"),
("Phylloscopus humei","淡眉柳莺"),("Phylloscopus borealis","极北柳莺"),
("Phylloscopus tenellipes","淡脚柳莺"),("Phylloscopus borealoides","双斑绿柳莺"),
("Phylloscopus magnirostris","大嘴柳莺"),("Phylloscopus trochiloides","暗绿柳莺"),
("Phylloscopus plumbeitarsus","铅色柳莺"),("Phylloscopus claudiae","灰脚柳莺"),
("Phylloscopus coronatus","冕柳莺"),("Phylloscopus ijimae","饭岛柳莺"),
("Phylloscopus reguloides","冠纹柳莺"),("Phylloscopus davisoni","白斑尾柳莺"),
("Phylloscopus goodsoni","哈氏冠纹柳莺"),("Phylloscopus emeiensis","峨眉柳莺"),
("Phylloscopus hainanus","海南柳莺"),("Phylloscopus calciatilis","石灰岩柳莺"),
("Phylloscopus ricketti","棕脸鹟莺"),("Phylloscopus cantator","黄腹鹟莺"),
("Phylloscopus castaniceps","栗头鹟莺"),("Phylloscopus valentini","比氏鹟莺"),
("Phylloscopus yunnanensis","云南柳莺"),("Phylloscopus sibilatrix","林柳莺"),
("Phylloscopus collybita","叽喳柳莺"),("Phylloscopus sindianus","东方叽喳柳莺"),
("Phylloscopus tytleri","提氏柳莺"),("Phylloscopus fuligiventer","棕腹柳莺"),
("Phylloscopus pulcher","橙斑翅柳莺"),("Phylloscopus maculipennis","灰冠柳莺"),
("Phylloscopus occisinensis","西藏柳莺"),("Phylloscopus chloronotus","灰喉柳莺"),
("Phylloscopus sichuanensis","四川柳莺"),("Phylloscopus forresti","丽山柳莺"),
("Phylloscopus ogilviegranti","白斑尾柳莺"),("Seicercus burkii","金眶鹟莺"),
("Seicercus omeiensis","峨眉鹟莺"),("Seicercus soror","比氏鹟莺"),
("Seicercus whistleri","灰冠鹟莺"),("Seicercus affinis","白眶鹟莺"),
("Seicercus castaniceps","栗头鹟莺"),("Seicercus valentini","比氏鹟莺"),
# Acrocephalidae 苇莺科
("Acrocephalus orientalis","东方大苇莺"),("Acrocephalus stentoreus","噪大苇莺"),
("Acrocephalus arundinaceus","大苇莺"),("Acrocephalus concinens","靛冠苇莺"),
("Acrocephalus bistrigiceps","双眉苇莺"),("Acrocephalus tangorum","远东苇莺"),
("Acrocephalus dumetorum","布氏苇莺"),("Acrocephalus agricola","稻田苇莺"),
("Acrocephalus aedon","厚嘴苇莺"),("Iduna caligata","靴篱莺"),
("Iduna rama","赛氏篱莺"),
# Locustellidae 蝗莺科
("Locustella lanceolata","矛斑蝗莺"),("Locustella naevia","小蝗莺"),
("Locustella certhiola","北蝗莺"),("Locustella ochotensis","苍眉蝗莺"),
("Locustella pleskei","史氏蝗莺"),("Locustella fasciolata","大蝗莺"),
("Locustella mandelli","中华短翅蝗莺"),("Locustella pryeri","沼泽蝗莺"),
("Helopsaltes amnicola","远东树莺"),("Bradypterus davidi","北短翅莺"),
("Bradypterus thoracicus","短翅莺"),("Bradypterus kashmirensis","棕色短翅莺"),
("Bradypterus luteoventris","棕褐短翅莺"),
# Cisticolidae 扇尾莺科
("Cisticola juncidis","棕扇尾莺"),("Cisticola exilis","金头扇尾莺"),
("Prinia gracilis","纯色鹪莺"),("Prinia hodgsonii","灰腹鹪莺"),
("Prinia flaviventris","黄腹鹪莺"),("Prinia inornata","褐头鹪莺"),
("Prinia polychroa","棕翅鹪莺"),("Prinia crinigera","山鹪莺"),
("Prinia subflava","暗冕鹪莺"),("Orthotomus sutorius","长尾缝叶莺"),
# Scotocercidae 鹟莺科
("Tickellia hodgsoni","金头缝叶莺"),("Tesia olivea","金冠地莺"),
("Tesia cyaniventer","灰腹地莺"),
# Sylviidae 莺科
("Sylvia curruca","白喉林莺"),("Sylvia communis","灰白喉林莺"),
("Sylvia nisoria","横斑林莺"),("Curruca althaea","荒漠林莺"),
("Curruca nana","沙漠林莺"),("Curruca minula","小林莺"),
("Fulvetta vinipectus","棕头鸦雀"),("Fulvetta striaticollis","华西鸦雀"),
("Lioparus chrysotis","金色鸦雀"),
# Paradoxornithidae 鸦雀科
("Paradoxornis heudei","震旦鸦雀"),("Suthora nipalensis","褐翅鸦雀"),
("Suthora verreauxi","灰冠鸦雀"),("Suthora fulvifrons","棕额鸦雀"),
("Suthora webbianus","棕头鸦雀"),("Suthora alphonsianus","灰头鸦雀"),
("Suthora conspicillatus","白眶鸦雀"),("Suthora davidianus","短尾鸦雀"),
("Suthora atrosuperciliaris","黑眉鸦雀"),("Suthora gularis","灰喉鸦雀"),
("Chleuasicus atrosuperciliaris","暗绿鸦雀"),("Paradoxornis zappeyi","暗色鸦雀"),
("Paradoxornis paradoxus","三趾鸦雀"),("Paradoxornis unicolor","褐鸦雀"),
("Conostoma aemodium","红嘴鸦雀"),("Cholornis unicolor","褐鸦雀"),
("Sinosuthora conspicillata","白眶鸦雀"),("Sinosuthora webbiana","棕头鸦雀"),
# Zosteropidae 绣眼鸟科
("Zosterops japonicus","暗绿绣眼鸟"),("Zosterops simplex","灰腹绣眼鸟"),
("Zosterops erythropleurus","红胁绣眼鸟"),("Zosterops palpebrosus","灰腹绣眼鸟"),
("Zosterops meyeni","黄腹绣眼鸟"),("Heleia squamifrons","鳞额绣眼鸟"),
# Timaliidae 雀鹛科
("Timalia pileata","红冠雀鹛"),("Chrysomma sinense","黄嘴薮鹛"),
("Chrysomma altirostre","褐山鹪莺"),("Graminicola bengalensis","大草莺"),
("Pomatorhinus ruficollis","棕颈钩嘴鹛"),("Pomatorhinus schisticeps","灰头钩嘴鹛"),
("Pomatorhinus ferruginosus","红嘴钩嘴鹛"),("Pomatorhinus ochraceiceps","棕头钩嘴鹛"),
("Pomatorhinus gravivox","棕颈钩嘴鹛"),("Stachyridopsis rufifrons","红额穗鹛"),
("Stachyridopsis ruficeps","红头穗鹛"),("Mixornis gularis","纹胸穗鹛"),
("Erythrogenys erythrogenys","锈脸钩嘴鹛"),("Erythrogenys swinhoei","灰肋噪鹛"),
# Leiothrichidae 噪鹛科
("Cutia nipalensis","斑翅鹛"),
("Garrulax perspicillatus","黑脸噪鹛"),("Garrulax monileger","白喉噪鹛"),
("Garrulax pectoralis","斑胸噪鹛"),("Garrulax lugubris","黑噪鹛"),
("Garrulax maesi","灰翅噪鹛"),("Garrulax sannio","白颊噪鹛"),
("Garrulax canorus","画眉"),("Garrulax taewanus","台湾画眉"),
("Garrulax cineraceus","灰胸薮鹛"),("Garrulax davidi","山噪鹛"),
("Garrulax subunicolor","棕噪鹛"),("Garrulax affinis","黑顶噪鹛"),
("Garrulax chinensis","黑喉噪鹛"),("Garrulax virgatus","纹胸噪鹛"),
("Trochalopteron elliotii","橙翅噪鹛"),("Trochalopteron milnei","红尾噪鹛"),
("Trochalopteron formosum","丽色噪鹛"),("Trochalopteron affine","黑顶噪鹛"),
("Trochalopteron subunicolor","棕噪鹛"),("Trochalopteron squamatum","鳞胸噪鹛"),
("Ianthocincla maxima","大噪鹛"),("Ianthocincla ocellata","眼斑噪鹛"),
("Pterorhinus davidi","山鹛"),("Pterorhinus berthemyi","棕噪鹛"),
("Liocichla omeiensis","灰胸薮鹛"),("Liocichla steerii","黄胸薮鹛"),
("Liocichla phoenicea","红翅薮鹛"),("Liocichla ripponi","赤尾噪鹛"),
("Leiothrix argentauris","银耳相思鸟"),("Leiothrix lutea","红嘴相思鸟"),
("Heterophasia desgodinsi","灰头鹛"),("Heterophasia melanoleuca","黑白鹛"),
("Heterophasia pulchella","丽色奇鹛"),("Heterophasia picaoides","长尾奇鹛"),
("Minla cyanouroptera","蓝翅希鹛"),("Minla ignotincta","红尾希鹛"),
("Actinodura morrisoniana","台湾斑翅鹛"),("Actinodura souliei","棕头斑翅鹛"),
("Actinodura ramsayi","灰头斑翅鹛"),("Actinodura nipalensis","纹胸斑翅鹛"),
("Yuhina diademata","白领凤鹛"),("Yuhina castaniceps","栗耳凤鹛"),
("Yuhina flavicollis","黄颈凤鹛"),("Yuhina gularis","纹喉凤鹛"),
("Yuhina occipitalis","棕枕凤鹛"),("Yuhina nigrimenta","黑颏凤鹛"),
("Yuhina brunneiceps","台湾凤鹛"),("Yuhina zantholeuca","黄腹凤鹛"),
# Pellorneidae 幽鹛科
("Pellorneum ruficeps","棕头幽鹛"),("Pellorneum albiventre","白腹幽鹛"),
("Napothera brevicaudata","短尾鹩鹛"),("Napothera epilepidota","小鳞鹩鹛"),
("Rimator malacoptilus","长嘴鹩鹛"),("Spelaeornis troglodytoides","斑胸短翅鹛"),
("Spelaeornis formosus","黑喉短翅鹛"),("Schoeniparus dubius","灰眶雀鹛"),
("Schoeniparus brunneus","棕头雀鹛"),
# Alcippeidae 雀鹛科
("Alcippe morrisonia","灰眶雀鹛"),("Alcippe hueti","褐头雀鹛"),
("Alcippe ruficapilla","红头雀鹛"),("Alcippe cinereiceps","灰头雀鹛"),
# Elachuridae 丽鹛科
("Elachura formosa","丽鹛"),
# Pnoepygidae 鳞胸鹪鹛科
("Pnoepyga albiventer","鳞胸鹪鹛"),("Pnoepyga immaculata","台湾鹪鹛"),
("Pnoepyga pusilla","小鳞胸鹪鹛"),
# Sittidae 鳾科
("Sitta europaea","普通鳾"),("Sitta nagaensis","黑眉鳾"),
("Sitta cashmirensis","克什米尔鳾"),("Sitta himalayensis","白尾鳾"),
("Sitta villosa","黑头鳾"),("Sitta yunnanensis","滇鳾"),
("Sitta formosa","丽鳾"),("Sitta frontalis","绒额鳾"),
# Tichodromidae 旋壁雀科
("Tichodroma muraria","红翅旋壁雀"),
# Certhiidae 旋木雀科
("Certhia familiaris","旋木雀"),("Certhia hodgsoni","霍氏旋木雀"),
("Certhia himalayana","高山旋木雀"),("Certhia nipalensis","锈腹旋木雀"),
("Certhia tianquanensis","天全旋木雀"),
# Troglodytidae 鹪鹩科
("Troglodytes troglodytes","鹪鹩"),
# Cinclidae 河乌科
("Cinclus cinclus","河乌"),("Cinclus pallasii","褐河乌"),
# Sturnidae 椋鸟科
("Aplonis panayensis","菲律宾椋鸟"),("Spodiopsar cineraceus","灰椋鸟"),
("Spodiopsar sericeus","丝光椋鸟"),("Agropsar sturninus","北椋鸟"),
("Sturnia sinensis","灰背椋鸟"),("Sturnia malabarica","灰头椋鸟"),
("Pastor roseus","粉红椋鸟"),("Sturnus vulgaris","紫翅椋鸟"),
("Acridotheres tristis","家八哥"),("Acridotheres cristatellus","八哥"),
("Acridotheres javanicus","白尾八哥"),("Gracupica nigricollis","黑领椋鸟"),
("Gracula religiosa","鹩哥"),
# Turdidae 鸫科
("Geokichla citrina","橙头地鸫"),("Geokichla sibirica","白眉地鸫"),
("Zoothera dauma","虎斑地鸫"),("Zoothera aurea","虎鸫"),
("Zoothera dixoni","长嘴地鸫"),("Zoothera mollissima","光背地鸫"),
("Zoothera andromedae","黑喉地鸫"),("Turdus obscurus","白眉鸫"),
("Turdus pallidus","白腹鸫"),("Turdus chrysolaus","赤胸鸫"),
("Turdus celaenops","七岛鸫"),("Turdus kessleri","棕背黑头鸫"),
("Turdus feae","灰翅鸫"),("Turdus hortulorum","灰背鸫"),
("Turdus cardis","乌灰鸫"),("Turdus albocinctus","白环鸫"),
("Turdus mupinensis","宝兴歌鸫"),("Turdus dissimilis","黑胸鸫"),
("Turdus boulboul","灰翅鸫"),("Turdus merula","乌鸫"),
("Turdus mandarinus","中华乌鸫"),("Turdus atrogularis","黑喉鸫"),
("Turdus ruficollis","赤颈鸫"),("Turdus naumanni","红尾鸫"),
("Turdus eunomus","斑鸫"),("Turdus pilaris","田鸫"),
("Turdus iliacus","白眉歌鸫"),("Turdus viscivorus","槲鸫"),
("Myophonus caeruleus","紫啸鸫"),("Myophonus insularis","台湾紫啸鸫"),
# Muscicapidae 鹟科
("Muscicapa striata","斑鹟"),("Muscicapa griseisticta","灰纹鹟"),
("Muscicapa sibirica","乌鹟"),("Muscicapa dauurica","北灰鹟"),
("Muscicapa muttui","棕尾褐鹟"),("Muscicapa ferruginea","棕尾鹟"),
("Ficedula zanthopygia","黄眉姬鹟"),("Ficedula narcissina","黄眉鹟"),
("Ficedula mugimaki","鸲姬鹟"),("Ficedula strophiata","橙胸姬鹟"),
("Ficedula parva","红胸姬鹟"),("Ficedula albicilla","红喉姬鹟"),
("Ficedula hyperythra","棕胸蓝姬鹟"),("Ficedula hodgsonii","锈胸蓝姬鹟"),
("Ficedula westermanni","小仙鹟"),("Ficedula superciliaris","白眉姬鹟"),
("Ficedula tricolor","蓝额长脚鹟"),("Ficedula sapphira","蓝喉姬鹟"),
("Ficedula monileger","白喉姬鹟"),("Ficedula solitaris","锈胸姬鹟"),
("Ficedula elisae","黄腹鹟"),
("Niltava sundara","棕腹蓝仙鹟"),("Niltava grandis","大仙鹟"),
("Niltava macgrigoriae","小仙鹟"),("Niltava davidi","棕腹仙鹟"),
("Niltava vivida","棕腹蓝仙鹟"),
("Cyornis hainanus","海南蓝仙鹟"),("Cyornis brunneatus","白喉蓝鹟"),
("Cyornis glaucicomans","灰蓝姬鹟"),("Cyornis rubeculoides","蓝胸姬鹟"),
("Cyornis unicolor","纯蓝仙鹟"),
("Eumyias thalassinus","铜蓝鹟"),
("Copsychus saularis","鹊鸲"),("Copsychus malabaricus","白腰鹊鸲"),
("Saxicoloides fulicatus","印度鸲"),
("Phoenicurus ochruros","赭红尾鸲"),("Phoenicurus phoenicurus","欧亚红尾鸲"),
("Phoenicurus hodgsoni","黑喉红尾鸲"),("Phoenicurus schisticeps","灰顶红尾鸲"),
("Phoenicurus auroreus","北红尾鸲"),("Phoenicurus frontalis","蓝额红尾鸲"),
("Phoenicurus fuliginosus","铅色水鸲"),("Phoenicurus affinis","蓝背红尾鸲"),
("Phoenicurus erythronotus","棕背红尾鸲"),("Phoenicurus erythrogastrus","白顶红尾鸲"),
("Luscinia svecica","蓝喉歌鸲"),("Luscinia calliope","红喉歌鸲"),
("Luscinia pectardens","白点翅鸲"),("Calliope calliope","红喉歌鸲"),
("Calliope pectoralis","红腹红尾鸲"),("Calliope tschebaiewi","金胸歌鸲"),
("Larvivora sibilans","蓝歌鸲"),("Larvivora cyane","蓝歌鸲"),
("Larvivora brunnea","鳞胸鹟"),
("Irania gutturalis","白喉歌鸲"),
("Tarsiger cyanurus","红胁蓝尾鸲"),("Tarsiger rufilatus","喜山红尾鸲"),
("Tarsiger chrysaeus","金色林鸲"),("Tarsiger indicus","白眉林鸲"),
("Saxicola torquatus","黑喉石鵖"),("Saxicola maurus","东亚石鵖"),
("Saxicola stejnegeri","黑喉石鵖"),("Saxicola ferreus","灰林鵖"),
("Saxicola insignis","白喉石鵖"),("Saxicola caprata","白斑黑石鵖"),
("Oenanthe oenanthe","穗鵖"),("Oenanthe pleschanka","白顶鵖"),
("Oenanthe deserti","漠鵖"),("Oenanthe isabellina","沙鵖"),
("Monticola gularis","白喉矶鸫"),("Monticola rufiventris","栗腹矶鸫"),
("Monticola solitarius","蓝矶鸫"),("Monticola cinclorhynchus","蓝头矶鸫"),
("Chaimarrornis leucocephalus","白顶溪鸲"),
("Rhyacornis fuliginosa","红尾水鸲"),
("Enicurus scouleri","小燕尾"),("Enicurus immaculatus","黑背燕尾"),
("Enicurus schistaceus","灰背燕尾"),("Enicurus leschenaulti","白冠燕尾"),
("Enicurus maculatus","斑背燕尾"),
("Cochoa viridis","绿宽嘴鸫"),("Cochoa purpurea","紫宽嘴鸫"),
# Regulidae 戴菊科
("Regulus regulus","戴菊"),("Regulus goodfellowi","台湾戴菊"),
# Bombycillidae 太平鸟科
("Bombycilla garrulus","太平鸟"),("Bombycilla japonica","小太平鸟"),
# Prunellidae 岩鹨科
("Prunella collaris","领岩鹨"),("Prunella himalayana","褐岩鹨"),
("Prunella rubeculoides","红胸岩鹨"),("Prunella strophiata","棕眉山岩鹨"),
("Prunella montanella","棕眉岩鹨"),("Prunella fulvescens","褐岩鹨"),
("Prunella ocularis","黑脸岩鹨"),("Prunella atrogularis","黑喉岩鹨"),
("Prunella koslowi","贺兰山岩鹨"),
# Passeridae 麻雀科
("Passer domesticus","家麻雀"),("Passer montanus","树麻雀"),
("Passer rutilans","山麻雀"),("Passer cinnamomeus","棕额麻雀"),
("Petronia petronia","石雀"),("Montifringilla nivalis","白斑翅雪雀"),
("Montifringilla adamsi","黑翅雪雀"),("Pyrgilauda ruficollis","棕颈雪雀"),
("Pyrgilauda blanfordi","白斑翅雪雀"),("Pyrgilauda davidiana","褐翅雪雀"),
("Onychostruthus taczanowskii","白腰雪雀"),
# Estrildidae 梅花雀科
("Lonchura striata","白腰文鸟"),("Lonchura punctulata","斑文鸟"),
("Lonchura atricapilla","栗腹文鸟"),("Lonchura malacca","黑头文鸟"),
("Lonchura oryzivora","禾雀"),("Erythrura gouldiae","七彩文鸟"),
("Amandava amandava","红梅花雀"),
# Motacillidae 鹡鸰科
("Dendronanthus indicus","山鹡鸰"),("Motacilla alba","白鹡鸰"),
("Motacilla citreola","黄头鹡鸰"),("Motacilla cinerea","灰鹡鸰"),
("Motacilla tschutschensis","东方黄鹡鸰"),("Motacilla flava","西方黄鹡鸰"),
("Motacilla grandis","日本鹡鸰"),("Motacilla maderaspatensis","白眉鹡鸰"),
("Anthus richardi","理氏鹨"),("Anthus godlewskii","布氏鹨"),
("Anthus campestris","平原鹨"),("Anthus rufulus","田鹨"),
("Anthus trivialis","林鹨"),("Anthus hodgsoni","树鹨"),
("Anthus gustavi","水鹨"),("Anthus cervinus","红喉鹨"),
("Anthus roseatus","粉红胸鹨"),("Anthus spinoletta","水鹨"),
("Anthus rubescens","黄腹鹨"),
# Fringillidae 雀科
("Fringilla montifringilla","燕雀"),("Fringilla coelebs","苍头燕雀"),
("Coccothraustes coccothraustes","锡嘴雀"),("Eophona migratoria","黑尾蜡嘴雀"),
("Eophona personata","黑头蜡嘴雀"),("Mycerobas icterioides","黑翅蜡嘴雀"),
("Mycerobas affinis","白点翅拟蜡嘴雀"),("Mycerobas melanozanthos","黄颈拟蜡嘴雀"),
("Mycerobas carnipes","白斑翅拟蜡嘴雀"),("Pinicola enucleator","松雀"),
("Carpodacus erythrinus","普通朱雀"),("Carpodacus roseus","粉红腹岭雀"),
("Carpodacus rubescens","淡腹朱雀"),("Carpodacus trifasciatus","三斑朱雀"),
("Carpodacus rubicilla","大朱雀"),("Carpodacus rubicilloides","拟大朱雀"),
("Carpodacus thura","白眉朱雀"),("Carpodacus rhodochlamys","红胸朱雀"),
("Carpodacus vinaceus","酒红朱雀"),("Carpodacus edwardsii","暗胸朱雀"),
("Carpodacus sipahi","火红朱雀"),("Carpodacus pulcherrimus","红眉朱雀"),
("Carpodacus roborowskii","藏雀"),("Carpodacus dubius","白喉朱雀"),
("Carpodacus formosanus","台湾朱雀"),("Carpodacus synoicus","大石朱雀"),
("Procarduelis nipalensis","暗胸朱雀"),
("Leucosticte nemoricola","林岭雀"),("Leucosticte brandti","褐翅岭雀"),
("Leucosticte sillemi","淡腹岭雀"),("Leucosticte arctoa","高山岭雀"),
("Pyrrhula nipalensis","棕头灰雀"),("Pyrrhula erythaca","灰头灰雀"),
("Pyrrhula pyrrhula","灰雀"),("Pyrrhula murina","青灰雀"),
("Chloris sinica","金翅雀"),("Linaria cannabina","赤胸朱顶雀"),
("Linaria flavirostris","黄嘴朱顶雀"),("Acanthis flammea","白腰朱顶雀"),
("Acanthis hornemanni","极北朱顶雀"),
("Carduelis carduelis","红额金翅雀"),("Spinus spinus","黄雀"),
("Spinus thibetanus","藏黄雀"),
("Loxia curvirostra","红交嘴雀"),("Loxia leucoptera","白翅交嘴雀"),
# Emberizidae 鹀科
("Emberiza citrinella","黄鹀"),("Emberiza leucocephalos","白头鹀"),
("Emberiza cioides","三道眉草鹀"),("Emberiza cia","灰眉岩鹀"),
("Emberiza godlewskii","戈氏岩鹀"),("Emberiza hortulana","圃鹀"),
("Emberiza buchanani","灰颈鹀"),("Emberiza rustica","田鹀"),
("Emberiza pusilla","小鹀"),("Emberiza chrysophrys","黄眉鹀"),
("Emberiza elegans","黄喉鹀"),("Emberiza aureola","黄胸鹀"),
("Emberiza spodocephala","灰头鹀"),("Emberiza sulphurata","硫黄鹀"),
("Emberiza tristrami","白眉鹀"),("Emberiza fucata","栗斑腹鹀"),
("Emberiza pallasi","苇鹀"),("Emberiza schoeniclus","芦鹀"),
("Emberiza yessoensis","北鹀"),("Emberiza jankowskii","栗耳鹀"),
("Emberiza variabilis","灰鹀"),("Emberiza rutila","栗鹀"),
("Emberiza melanocephala","黑头鹀"),("Emberiza bruniceps","褐头鹀"),
("Melophus lathami","凤头鹀"),("Latoucheornis siemsseni","藏鹀"),
("Granativora koslowi","黄胸鹀"),("Cristemberiza elegans","凤头鹀"),
# Calcariidae 铁爪鹀科
("Calcarius lapponicus","铁爪鹀"),("Plectrophenax nivalis","雪鹀"),
# Nectariniidae 太阳鸟科
("Aethopyga gouldiae","蓝喉太阳鸟"),("Aethopyga nipalensis","绿尾太阳鸟"),
("Aethopyga ignicauda","火尾太阳鸟"),("Aethopyga saturata","黑胸太阳鸟"),
("Aethopyga siparaja","黄腰太阳鸟"),("Aethopyga christinae","叉尾太阳鸟"),
("Arachnothera longirostra","长嘴捕蛛鸟"),("Arachnothera magna","纹背捕蛛鸟"),
("Cinnyris jugularis","黄腹花蜜鸟"),
# Dicaeidae 啄花鸟科
("Dicaeum cruentatum","红胸啄花鸟"),("Dicaeum ignipectus","红胸啄花鸟"),
("Dicaeum minullum","纯色啄花鸟"),("Dicaeum concolor","纯色啄花鸟"),
("Dicaeum agile","厚嘴啄花鸟"),
# Chloropseidae 叶鹎科
("Chloropsis hardwickii","橙腹叶鹎"),("Chloropsis aurifrons","金额叶鹎"),
("Chloropsis cochinchinensis","蓝翅叶鹎"),
# Irenidae 和平鸟科
("Irena puella","和平鸟"),
# Vireonidae 绿鹃科
("Vireo gilvus","灰绿鹃"),("Erpornis zantholeuca","白腹凤鹛"),
("Pteruthius aeralatus","淡绿鵙鹛"),("Pteruthius melanotis","栗喉鵙鹛"),
("Pteruthius xanthochlorus","绿鵙鹛"),("Pteruthius flaviscapis","棕额鵙鹛"),
]
