export {
  getHealthStatus,
  getApiErrorMessage,
  analyzeAudio,
  getSpeciesList,
  getSpeciesRecordings,
  getSurveySites,
  createSurveySite,
  removeSurveySite,
  getEBirdKeyStatus,
  setEBirdKey,
  getEBirdRegions,
  getEBirdRecentObs,
  getEBirdNotableObs,
  getEBirdHotspots,
  getEBirdSpeciesList,
  getComprehensiveBiodiversity,
  getPreSurveySpecies,
  batchScanDirectory,
  analyzeTrapImage,
  getTrapRecords,
  analyzeImage,
  getImageRecords,
  compareSpectrograms,
  searchXenoCanto,
  compareSites,
  getPlatformConfig,
  getPaperContext,
  getSurveyProjects,
  createSurveyProject,
  deleteSurveyProject,
  getFieldSurveySites,
  createFieldSurveySite,
  deleteFieldSurveySite,
  getSurveyRoutes,
  createSurveyRoute,
  deleteSurveyRoute,
  importSurveyRoute,
  exportSurveyRoute,
  getSurveyRouteSummary,
  exportSurveyRouteReport,
  getSurveyObservations,
  createSurveyObservation,
  deleteSurveyObservation,
  getSurveyTracks,
  createSurveyTrack,
  createOfflineMapPackage,
  pushSurveySync,
  pullSurveySync,
  getSurveyProtocols,
  getSurveyTaxonomyPackages,
  searchSurveyTaxonomy,
  getSurveyDesignAssets,
  createSurveyDesignAsset,
  getSurveyEvents,
  createSurveyEvent,
  createSurveyExportJob,
  getXCKeyStatus,
  setXCKey,
  getDevices,
  getOnlineDevices,
  getDeviceMap,
  registerDevice,
  removeDevice,
  getMonitoringSessions,
  getMonitoringDashboard,
  getSessionDetail,
  getUnverifiedDetections,
  verifyDetection,
  batchVerifyDetections,
  getDetectionStats,
  getSessionDetections,
  getSiteDetections,
  getOccupancyData,
  getEmbeddingStats,
  getEmbeddingCluster,
  getEmbeddingSimilarity,
  getNovelSounds,
  getGBIFOccurrences,
  getINatObservations,
  getBirdNETStatus,
  analyzeBirdNET,
  compareEngines,
  exportDetectionsCSV,
  analyzeBatch,
  generateReport,
  createDeviceSocket,
  normalizeHealthStatus,
  normalizeDeviceType,
  normalizeDeviceRecord,
  normalizeDeviceMarker,
  normalizeMonitoringSession,
  normalizeMonitoringDashboard,
  normalizeEmbeddingStats,
  normalizeSurveyProtocolDefinition,
  normalizeSurveyTaxonomyEntry,
  normalizeSurveyTaxonomyPackage,
  resolveConfiguredApiBases,
  resolveApiTransportConfig,
} from './api'

export {
  loadSurveyState,
  saveSurveyState,
  emptySurveyState,
  mergeStoredSurveyState,
  mergeRecords,
  mergeSyncPull,
  applySyncResult,
  upsertLocalEntity,
  replaceEntity,
  normalizeJurisdiction,
  getDeviceId,
  lineDistanceMeters,
  parseRouteFile,
  buildFeatureCollection,
  buildGpx,
  downloadTextFile,
  snapObservationToRoutes,
  prefetchMapTiles,
  formatBytes,
  createDefaultProject,
  filterByProject,
  filterBySite,
  filterByProgram,
  filterByProtocol,
  filterByJurisdiction,
  filterSurveyRecords,
  deriveSurveyTaxonomyPackageStatus,
  serializeAttachment,
  restoreDraftAttachment,
  restoreDraftAttachments,
} from './surveyOffline'

export { PlatformConfigProvider, usePlatformConfig } from './PlatformConfigContext'

export {
  shannonWiener,
  simpson,
  simpsonDominance,
  pielouEvenness,
  margalefRichness,
  speciesRichness,
  totalAbundance,
  dominanceIndex,
  bergerParkerIndex,
  calculateAllIndices,
  buildSpeciesTable,
} from './diversityIndices'

export {
  estimateTileDownload,
  downloadTiles,
  getCachedTile,
  getTileCacheStats,
  clearTileCache,
  boundsFromCenter,
} from './tileCache'

export {
  isNativeMobile,
  loadNativeSurveyState,
  saveNativeSurveyState,
  requestNativeCurrentPosition,
  startNativePositionWatch,
  stopNativePositionWatch,
  capturePhotoAttachment,
  pulseFeedback,
  CameraSource,
  ImpactStyle,
} from './mobileNative'

export {
  createEmptyTrackDraft,
  normalizeTrackDraft,
  buildTrackDraftForStart,
  resolveDraftAttachments,
  attachmentListsMatch,
  normalizeAttachmentIds,
} from './fieldOpsDrafts'

export {
  createAttachmentId,
  getAttachmentLookupId,
  normalizeAttachmentContract,
  applyAttachmentContext,
  computeAttachmentChecksum,
  computeAttachmentChecksumFromBase64,
} from './attachmentContract'
