export const TAXA = ['birds', 'mammals', 'amphibians', 'reptiles', 'plants', 'insects', 'traces']
export const DEFAULT_REMOTE_TILE_URL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
export const DEFAULT_FIELD_TILE_PROXY_URL = '/api/maps/tiles/{z}/{x}/{y}'

export const PROGRAM_OPTIONS = [
  {
    id: 'terrestrial_vertebrates',
    label: 'Terrestrial vertebrates',
    description: 'Bird surveys, point counts, mammal trapping, and herp camera work share one field shell.',
  },
  {
    id: 'plants',
    label: 'Plants',
    description: 'Quadrat and transect vegetation recording stays isolated from vertebrate workflows.',
  },
  {
    id: 'insects',
    label: 'Insects',
    description: 'Insect transects keep their own effort and record fields while syncing to the same backend.',
  },
]

export const TERRESTRIAL_VERTEBRATE_PROTOCOLS = new Set([
  'bird_line_transect',
  'bird_point_count',
  'mammal_trap_net',
  'herp_infrared_camera',
])

export const VERTEBRATE_SUBMODULES = [
  {
    id: 'birds',
    label: 'Birds',
    taxonGroup: 'birds',
    protocolIds: ['bird_line_transect', 'bird_point_count'],
  },
  {
    id: 'mammals',
    label: 'Mammals',
    taxonGroup: 'mammals',
    protocolIds: ['mammal_trap_net'],
  },
  {
    id: 'amphibians',
    label: 'Amphibians',
    taxonGroup: 'amphibians',
    protocolIds: ['herp_infrared_camera'],
  },
  {
    id: 'reptiles',
    label: 'Reptiles',
    taxonGroup: 'reptiles',
    protocolIds: ['herp_infrared_camera'],
  },
]

export const EXPORT_JURISDICTIONS = [
  { id: 'mainland_china', label: 'Mainland China' },
  { id: 'taiwan', label: 'Taiwan' },
]

export const PROTOCOL_OPTIONS = [
  {
    id: 'bird_line_transect',
    program: 'terrestrial_vertebrates',
    label: 'Bird line transect',
    shellLabel: 'Transect walk',
    description: 'Walk one route and record birds with route-linked detections and effort.',
    assetLabel: 'Transect route',
    assetHint: 'Select or import the transect line used for the bird walk.',
    requiresAsset: true,
    supportsTrack: true,
    defaultTaxonGroup: 'birds',
    defaultEvidenceType: 'visual',
    vertebrateSubmodules: ['birds'],
    allowedTaxonGroups: ['birds'],
    eventFields: [
      { key: 'transect_name', label: 'Transect name', placeholder: 'North ridge transect', required: true },
      { key: 'transect_length_m', label: 'Transect length (m)', type: 'number', placeholder: '1200', required: true },
      { key: 'survey_round', label: 'Survey round', placeholder: 'Round 1', required: true },
      { key: 'observer_count', label: 'Observer count', type: 'number', placeholder: '2', required: true },
      { key: 'distance_walked_m', label: 'Distance walked (m)', type: 'number', placeholder: '1150', required: true },
      { key: 'duration_min', label: 'Duration (min)', type: 'number', placeholder: '65', required: true },
      { key: 'pace_m_per_min', label: 'Pace (m/min)', type: 'number', placeholder: '18' },
      { key: 'wind_code', label: 'Wind code', placeholder: '0-5' },
      { key: 'cloud_code', label: 'Cloud code', placeholder: '0-10' },
      { key: 'precipitation_code', label: 'Precipitation code', placeholder: 'none / light / rain' },
      { key: 'habitat_type', label: 'Habitat type', placeholder: 'Evergreen broadleaf forest' },
      { key: 'disturbance_notes', label: 'Disturbance notes', placeholder: 'Trail traffic near lower section' },
    ],
    recordFields: [
      { key: 'detection_type', label: 'Detection type', placeholder: 'seen / heard / mixed', required: true },
      { key: 'distance_band', label: 'Distance band', placeholder: '0-25m', required: true },
      { key: 'bearing', label: 'Bearing', placeholder: 'NE / 35°' },
      { key: 'breeding_code', label: 'Breeding code', placeholder: 'A / B / C' },
      { key: 'flock_size', label: 'Flock size', type: 'number', placeholder: '6' },
      { key: 'route_segment_id', label: 'Route segment ID', placeholder: 'seg-02' },
    ],
  },
  {
    id: 'bird_point_count',
    program: 'terrestrial_vertebrates',
    label: 'Bird point count',
    shellLabel: 'Point count station',
    description: 'Use one fixed station or short segment and capture count duration and radius.',
    assetLabel: 'Point count asset',
    assetHint: 'Select a station route or segment if one is available for this point count.',
    requiresAsset: false,
    supportsTrack: false,
    defaultTaxonGroup: 'birds',
    defaultEvidenceType: 'audio',
    vertebrateSubmodules: ['birds'],
    allowedTaxonGroups: ['birds'],
    eventFields: [
      { key: 'point_id', label: 'Point ID', placeholder: 'PC-01', required: true },
      { key: 'point_visit_index', label: 'Visit index', type: 'number', placeholder: '1', required: true },
      { key: 'point_duration_min', label: 'Point duration (min)', type: 'number', placeholder: '10', required: true },
      { key: 'observer_count', label: 'Observer count', type: 'number', placeholder: '1', required: true },
      { key: 'point_radius_m', label: 'Point radius (m)', type: 'number', placeholder: '100' },
      { key: 'station_count', label: 'Station count', type: 'number', placeholder: '1' },
      { key: 'travel_distance_m', label: 'Travel distance (m)', type: 'number', placeholder: '0' },
      { key: 'wind_code', label: 'Wind code', placeholder: '0-5' },
      { key: 'cloud_code', label: 'Cloud code', placeholder: '0-10' },
      { key: 'precipitation_code', label: 'Precipitation code', placeholder: 'none / drizzle' },
      { key: 'habitat_type', label: 'Habitat type', placeholder: 'Forest edge' },
    ],
    recordFields: [
      { key: 'detection_type', label: 'Detection type', placeholder: 'heard / seen', required: true },
      { key: 'distance_band', label: 'Distance band', placeholder: '0-50m', required: true },
      { key: 'breeding_code', label: 'Breeding code', placeholder: 'A / B / C' },
      { key: 'point_id', label: 'Point ID override', placeholder: 'PC-01' },
      { key: 'flock_size', label: 'Flock size', type: 'number', placeholder: '3' },
    ],
  },
  {
    id: 'mammal_trap_net',
    program: 'terrestrial_vertebrates',
    label: 'Mammal trap / net',
    shellLabel: 'Trap or net event',
    description: 'Track trap lines, net checks, and specimen or release records for mammals.',
    assetLabel: 'Trap or net asset',
    assetHint: 'Select a trap line or station route if you want the captures tied to one asset.',
    requiresAsset: false,
    supportsTrack: false,
    defaultTaxonGroup: 'mammals',
    defaultEvidenceType: 'trace',
    vertebrateSubmodules: ['mammals'],
    allowedTaxonGroups: ['mammals'],
    eventFields: [
      { key: 'trap_method', label: 'Trap / net method', placeholder: 'Sherman trap / mist net', required: true },
      { key: 'trap_station_count', label: 'Trap station count', type: 'number', placeholder: '12', required: true },
      { key: 'deployment_start_time', label: 'Deployment start time', placeholder: '2026-04-19T18:00:00Z', required: true },
      { key: 'deployment_end_time', label: 'Deployment end time', placeholder: '2026-04-20T06:00:00Z', required: true },
      { key: 'bait_type', label: 'Bait type', placeholder: 'peanut + oats', required: true },
      { key: 'observer_count', label: 'Observer count', type: 'number', placeholder: '2', required: true },
      { key: 'trap_model', label: 'Trap model', placeholder: 'Sherman folding' },
      { key: 'check_interval_h', label: 'Check interval (h)', type: 'number', placeholder: '12' },
      { key: 'microhabitat', label: 'Microhabitat', placeholder: 'Bamboo understory' },
      { key: 'permit_reference', label: 'Permit reference', placeholder: 'Permit-2026-01' },
      { key: 'welfare_notes', label: 'Welfare notes', placeholder: 'Shade checked, water provided' },
      { key: 'trap_nights', label: 'Trap nights', type: 'number', placeholder: '24' },
      { key: 'active_trap_count', label: 'Active trap count', type: 'number', placeholder: '12' },
      { key: 'checked_station_count', label: 'Checked station count', type: 'number', placeholder: '12' },
    ],
    recordFields: [
      { key: 'capture_status', label: 'Capture status', placeholder: 'captured / empty / disturbed', required: true },
      { key: 'trap_station_id', label: 'Trap station ID', placeholder: 'MAM-05', required: true },
      { key: 'mark_code', label: 'Mark code', placeholder: 'ear-tag-12' },
      { key: 'sex', label: 'Sex', placeholder: 'male / female / unknown' },
      { key: 'life_stage', label: 'Life stage', placeholder: 'adult / juvenile' },
      { key: 'body_mass_g', label: 'Body mass (g)', type: 'number', placeholder: '120' },
      { key: 'release_status', label: 'Release status', placeholder: 'released / retained / escaped' },
      { key: 'sample_collected', label: 'Sample collected', placeholder: 'hair / feces / blood / none' },
    ],
  },
  {
    id: 'herp_infrared_camera',
    program: 'terrestrial_vertebrates',
    label: 'Herp infrared camera',
    shellLabel: 'Infrared camera station',
    description: 'Deploy, check, and retrieve infrared cameras for amphibians and reptiles.',
    assetLabel: 'Camera station',
    assetHint: 'Select a camera station or route if one has already been planned for this site.',
    requiresAsset: false,
    supportsTrack: false,
    defaultTaxonGroup: 'amphibians',
    defaultEvidenceType: 'visual',
    vertebrateSubmodules: ['amphibians', 'reptiles'],
    allowedTaxonGroups: ['amphibians', 'reptiles'],
    eventFields: [
      { key: 'camera_station_id', label: 'Camera station ID', placeholder: 'HERP-CAM-02', required: true },
      { key: 'camera_action', label: 'Camera action', placeholder: 'deploy / check / retrieve', required: true },
      { key: 'deployment_start_time', label: 'Deployment start time', placeholder: '2026-04-19T18:00:00Z', required: true },
      { key: 'deployment_end_time', label: 'Deployment end time', placeholder: '2026-04-29T18:00:00Z', required: true },
      { key: 'camera_model', label: 'Camera model', placeholder: 'HC550M', required: true },
      { key: 'observer_count', label: 'Observer count', type: 'number', placeholder: '2', required: true },
      { key: 'sensor_mode', label: 'Sensor mode', placeholder: 'IR motion / time lapse' },
      { key: 'trigger_interval_s', label: 'Trigger interval (s)', type: 'number', placeholder: '30' },
      { key: 'camera_height_cm', label: 'Camera height (cm)', type: 'number', placeholder: '25' },
      { key: 'orientation', label: 'Orientation', placeholder: 'SE / 135°' },
      { key: 'bait_lure', label: 'Bait / lure', placeholder: 'none / fish oil' },
      { key: 'habitat', label: 'Habitat', placeholder: 'stream bank' },
      { key: 'camera_days', label: 'Camera days', type: 'number', placeholder: '10' },
      { key: 'active_camera_count', label: 'Active camera count', type: 'number', placeholder: '4' },
      { key: 'file_count', label: 'File count', type: 'number', placeholder: '240' },
    ],
    recordFields: [
      { key: 'camera_station_id', label: 'Camera station ID', placeholder: 'HERP-CAM-02', required: true },
      { key: 'individual_count', label: 'Individual count', type: 'number', placeholder: '1' },
      { key: 'life_stage', label: 'Life stage', placeholder: 'adult / juvenile / larva' },
      { key: 'media_file_id', label: 'Media file ID', placeholder: 'IMG_0001' },
      { key: 'sequence_id', label: 'Sequence ID', placeholder: 'SEQ-12' },
    ],
  },
  {
    id: 'plant_quadrat',
    program: 'plants',
    label: 'Plant quadrat',
    shellLabel: 'Quadrat event',
    description: 'Record one vegetation quadrat with area, layer, cover, and species attributes.',
    assetLabel: 'Quadrat asset',
    assetHint: 'Select a plot or small route segment if you have one prepared for this quadrat.',
    requiresAsset: false,
    supportsTrack: false,
    defaultTaxonGroup: 'plants',
    defaultEvidenceType: 'visual',
    eventFields: [
      { key: 'quadrat_code', label: 'Quadrat code', placeholder: 'Q-01' },
      { key: 'quadrat_area_m2', label: 'Quadrat area (m2)', type: 'number', placeholder: '1' },
      { key: 'vegetation_layer', label: 'Vegetation layer', placeholder: 'Tree / shrub / herb' },
    ],
    recordFields: [
      { key: 'cover_percent', label: 'Cover (%)', type: 'number', placeholder: '30' },
      { key: 'height_cm', label: 'Height (cm)', type: 'number', placeholder: '45' },
      { key: 'phenology', label: 'Phenology', placeholder: 'Flowering / fruiting / vegetative' },
    ],
  },
  {
    id: 'plant_transect',
    program: 'plants',
    label: 'Plant transect',
    shellLabel: 'Vegetation transect',
    description: 'Use route-linked segments for vegetation transects and layer-based records.',
    assetLabel: 'Plant transect',
    assetHint: 'Select or import the vegetation transect used for this sampling event.',
    requiresAsset: true,
    supportsTrack: true,
    defaultTaxonGroup: 'plants',
    defaultEvidenceType: 'visual',
    eventFields: [
      { key: 'segment_length_m', label: 'Segment length (m)', type: 'number', placeholder: '100' },
      { key: 'transect_width_m', label: 'Transect width (m)', type: 'number', placeholder: '5' },
      { key: 'vegetation_layer', label: 'Vegetation layer', placeholder: 'Tree / shrub / herb' },
    ],
    recordFields: [
      { key: 'cover_percent', label: 'Cover (%)', type: 'number', placeholder: '40' },
      { key: 'height_cm', label: 'Height (cm)', type: 'number', placeholder: '120' },
      { key: 'growth_form', label: 'Growth form', placeholder: 'Tree / shrub / vine / herb' },
    ],
  },
  {
    id: 'insect_transect',
    program: 'insects',
    label: 'Insect transect',
    shellLabel: 'Insect transect',
    description: 'Walk a transect and capture insect counts with weather and detection context.',
    assetLabel: 'Insect transect',
    assetHint: 'Select or import the transect segment used for the insect survey.',
    requiresAsset: true,
    supportsTrack: true,
    defaultTaxonGroup: 'insects',
    defaultEvidenceType: 'visual',
    eventFields: [
      { key: 'transect_width_m', label: 'Transect width (m)', type: 'number', placeholder: '5' },
      { key: 'weather_window', label: 'Weather window', placeholder: 'Sunny, low wind' },
      { key: 'pace_note', label: 'Walk pace', placeholder: 'Constant pace / sweep count' },
    ],
    recordFields: [
      { key: 'life_stage', label: 'Life stage', placeholder: 'Adult / larva / pupa' },
      { key: 'distance_band_m', label: 'Distance band (m)', type: 'number', placeholder: '2' },
      { key: 'behavior_code', label: 'Behavior code', placeholder: 'Flying / basking / feeding' },
    ],
  },
]

export const COPY = {
  en: {
    badge: 'Offline Biodiversity Survey',
    title: 'Biodiversity field survey workspace',
    body: 'Prepare routes or stations, cache offline maps, capture observations and attachments, restore sessions after interruptions, and sync safely when a connection returns.',
    pilotTitle: 'Release workflow',
    pilotBody: 'Complete route, station, or quadrat work offline on Android, then restore, sync, and export without developer intervention.',
    offline: 'Offline',
    online: 'Online',
    pull: 'Pull',
    push: 'Push',
    project: 'Project',
    projectPlaceholder: 'Project name',
    regionPlaceholder: 'Region or reserve',
    createProject: 'Create project',
    site: 'Site',
    sitePlaceholder: 'Site name',
    habitatPlaceholder: 'Habitat type',
    saveSite: 'Save site',
    map: 'Offline map',
    transect: 'Route or station asset',
    selectTransect: 'Select asset',
    selectTransectHint: 'Select a route, station, or plot asset when the current protocol needs one.',
    preloadMap: 'Preload tiles',
    importRoute: 'Import route',
    exportGeoJSON: 'GeoJSON',
    exportGpx: 'GPX',
    observation: 'Quick observation',
    speciesPlaceholder: 'Chinese, English, or scientific name',
    evidenceVisual: 'Visual',
    evidenceAudio: 'Audio',
    evidenceTrace: 'Trace',
    saveObservation: 'Save observation',
    track: 'Track recorder',
    startTrack: 'Start track',
    stopTrack: 'Stop track',
    media: 'Media inbox',
    sync: 'Sync center',
    attachments: 'Attachments',
    capturePhoto: 'Take photo',
    captureAudioStart: 'Record audio',
    captureAudioStop: 'Stop audio',
    confidence: 'Confidence',
    count: 'Count',
    observer: 'Observer',
    weather: 'Weather',
    behavior: 'Behavior / notes',
    location: 'Use current GPS',
    noProject: 'A default field project will be created automatically if none exists.',
    routeSummary: 'Planned vs recorded',
    routeLength: 'Route length',
    recordsOnTransect: 'Observations',
    speciesLabel: 'species',
    effort: 'Effort',
    transectNotes: 'Event notes',
    walkStart: 'Event start',
    walks: 'walks',
    transectReport: 'Route or station report',
    loadingReport: 'Loading route or station summary...',
    reportOfflineHint: 'Reconnect to load the latest route or station summary and enable report exports.',
    emptyReportSummary: 'The server did not return a route or station summary for this selection yet.',
    noSpeciesRows: 'No species rows in this report yet.',
    noObservers: 'No observers listed',
    noWeather: 'No weather summary',
    speciesList: 'Species list',
    serverSummary: 'server summary',
    routeReady: 'Selected asset',
    routeMissing: 'Asset needed',
    walkActive: 'Walk active',
    walkIdle: 'Walk idle',
    syncBacklog: 'Sync backlog',
    routeSelectionStep: '1. Select or import the route, station, or plot asset for the active site.',
    walkRecordingStep: '2. Start a walk when the protocol is route-based so GPS effort and timing stay attached to that asset.',
    speciesRecordingStep: '3. Save observations with evidence, observer, taxonomy, and protocol-specific context.',
    syncReportStep: '4. Sync queued work and export the protocol bundle when online.',
    unknownTaxon: 'Unknown taxon',
    traceOnly: 'Trace only',
    queueEmpty: 'Nothing waiting in the sync queue.',
    conflicts: 'Conflicts',
    mapNote: 'Tile downloads use browser cache so the same area can reopen without network.',
  },
  zh: {
    badge: '离线外业调查',
    title: '中国野生动物外业调查工作区',
    body: '在同一个界面里完成调查项目管理、路线导入、离线底图缓存、轨迹记录、观察录入、媒体证据保存和联网后的安全同步。',
    offline: '离线',
    online: '在线',
    pull: '拉取',
    push: '推送',
    project: '项目',
    projectPlaceholder: '项目名称',
    regionPlaceholder: '保护地或区域',
    createProject: '新建项目',
    site: '样点',
    sitePlaceholder: '样点名称',
    habitatPlaceholder: '生境类型',
    saveSite: '保存样点',
    map: '离线地图',
    preloadMap: '缓存底图',
    importRoute: '导入路线',
    exportGeoJSON: '导出 GeoJSON',
    exportGpx: '导出 GPX',
    observation: '快速观察记录',
    speciesPlaceholder: '中文名、英文名或学名',
    evidenceVisual: '目击',
    evidenceAudio: '声音',
    evidenceTrace: '痕迹',
    saveObservation: '保存记录',
    track: '轨迹记录',
    startTrack: '开始记录',
    stopTrack: '结束记录',
    media: '媒体收件箱',
    sync: '同步中心',
    attachments: '附件',
    confidence: '可信度',
    count: '数量',
    observer: '观察者',
    behavior: '行为 / 备注',
    location: '使用当前 GPS',
    noProject: '如果本地还没有项目，会自动创建一个默认项目。',
    routeSummary: '计划路线与实走轨迹',
    unknownTaxon: '未知类群',
    traceOnly: '仅痕迹',
    queueEmpty: '当前没有待同步操作。',
    conflicts: '冲突',
    mapNote: '底图缓存使用浏览器 Cache API，同一区域在离线时也能再次打开。',
  },
}
