"""Pressure test ``POST /api/surveys/projects`` for the no-503 SLO.

What this script verifies:
    The work-order acceptance criterion is "Playwright 跑一次性能压测连续 200
    次 POST projects 零 503". We translate that into an in-process FastAPI
    TestClient session that runs the **full FastAPI lifespan** (so
    `_lifespan_startup` initializes survey_store / detection_store /
    taxonomy_catalog the same way it does under uvicorn / gunicorn), then
    fires 200 sequential ``POST /api/surveys/projects`` requests and asserts:

      * No response carries HTTP 503.
      * No response carries HTTP 500.
      * Every response carries an ``X-Request-ID`` header (the request_id
        middleware contract).
      * Every successful project create returns a non-empty ``project_id``
        we can later assert on.

What this script does NOT test:
    True concurrency / wall-clock latency. Use a dedicated load tool
    (locust, k6, wrk) against the deployed environment for that. The
    deterministic 503 cascade that this script reproduces — caused by an
    uninitialized store handed back to every request — does NOT need
    concurrency to surface.

Usage:
    python scripts/pressure_test_projects.py species          # default
    python scripts/pressure_test_projects.py acoustic
    python scripts/pressure_test_projects.py --requests 500
    python scripts/pressure_test_projects.py --json > pressure.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PLATFORM_BACKEND_DIRS = {
    "species": REPO_ROOT / "species_monitoring_platform" / "backend",
    "acoustic": REPO_ROOT / "acoustic_platform" / "backend",
}


def _stage_production_env() -> Path:
    """Set up the env vars that satisfy the no-demo runtime contract."""
    stage = Path(tempfile.mkdtemp(prefix="bird_platform_pressure_"))
    (stage / "data").mkdir(parents=True, exist_ok=True)
    (stage / "checkpoints").mkdir(parents=True, exist_ok=True)
    (stage / "frontend_dist").mkdir(parents=True, exist_ok=True)
    os.environ.setdefault("APP_ENV", "production")
    os.environ.setdefault("BIRD_API_KEY", "pressure-test-key")
    os.environ.setdefault("CORS_ORIGINS", "https://example.com")
    os.environ.setdefault("SURVEY_DATA_DIR", str(stage / "data"))
    os.environ.setdefault("CHECKPOINTS_DIR", str(stage / "checkpoints"))
    os.environ.setdefault("FRONTEND_DIST_DIR", str(stage / "frontend_dist"))
    os.environ.setdefault("BIRD_PLATFORM_OUTPUT_DIR", str(stage / "data"))
    # Survey-bucket rate limiter would normally cap us at 60 req/min and
    # produce noisy 429s that obscure the actual no-503 SLO signal. Lift
    # it for the pressure test only; production deploys keep the default.
    os.environ.setdefault("SURVEY_RATE_LIMIT", "100000")
    return stage


def run_pressure(platform: str, count: int) -> dict:
    backend_dir = PLATFORM_BACKEND_DIRS[platform]
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    if str(backend_dir) not in sys.path:
        sys.path.insert(0, str(backend_dir))

    stage = _stage_production_env()
    try:
        from fastapi.testclient import TestClient

        import main as backend_main

        api_key = os.environ["BIRD_API_KEY"]
        headers = {"X-API-Key": api_key}

        status_codes: Counter[int] = Counter()
        request_ids_seen = 0
        project_ids: list[str] = []
        sample_errors: list[dict] = []

        # The `with TestClient(...)` context manager runs the lifespan that
        # this exact patch fixes (survey_store / detection_store /
        # taxonomy_catalog asserted non-None post-startup).
        with TestClient(backend_main.app) as client:
            for i in range(count):
                payload = {
                    "name": f"PressureProject_{i:04d}",
                    "region": "scripted-pressure-test",
                    "team_members": ["pressure-bot"],
                    "target_taxa": ["birds"],
                    "notes": "Generated by scripts/pressure_test_projects.py",
                    "sync_state": "synced",
                }
                response = client.post(
                    "/api/surveys/projects",
                    json=payload,
                    headers=headers,
                )
                status_codes[response.status_code] += 1
                if response.headers.get("X-Request-ID"):
                    request_ids_seen += 1
                if response.status_code == 200:
                    try:
                        project_ids.append(
                            response.json().get("project", {}).get("project_id", "")
                        )
                    except ValueError:
                        sample_errors.append(
                            {"index": i, "status": 200, "detail": "non-JSON body"}
                        )
                elif response.status_code >= 400 and len(sample_errors) < 5:
                    try:
                        sample_errors.append(
                            {
                                "index": i,
                                "status": response.status_code,
                                "detail": response.json(),
                            }
                        )
                    except ValueError:
                        sample_errors.append(
                            {
                                "index": i,
                                "status": response.status_code,
                                "detail": response.text[:240],
                            }
                        )

        # Pass criteria from the work-order acceptance contract.
        five_oh_threes = status_codes.get(503, 0)
        five_hundreds = status_codes.get(500, 0)
        passed = (
            five_oh_threes == 0
            and five_hundreds == 0
            and request_ids_seen == count
        )

        return {
            "platform": platform,
            "requests_attempted": count,
            "status_codes": dict(status_codes),
            "five_oh_three_count": five_oh_threes,
            "five_hundred_count": five_hundreds,
            "request_id_header_count": request_ids_seen,
            "project_ids_created": len([pid for pid in project_ids if pid]),
            "passed": passed,
            "sample_errors": sample_errors,
        }
    finally:
        # Best-effort cleanup; OS tmpdir collector handles the rest.
        try:
            import shutil

            shutil.rmtree(stage, ignore_errors=True)
        except Exception:  # noqa: BLE001
            pass


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "platform",
        choices=sorted(PLATFORM_BACKEND_DIRS.keys()),
        nargs="?",
        default="species",
    )
    parser.add_argument(
        "--requests",
        "-n",
        type=int,
        default=200,
        help="Number of sequential POST requests to send (default: 200)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the result summary as JSON instead of human-readable text",
    )
    args = parser.parse_args()

    result = run_pressure(args.platform, args.requests)

    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print(f"== Pressure test · POST /api/surveys/projects · {args.platform} ==")
        print(f"  attempted        : {result['requests_attempted']}")
        print(f"  status codes     : {result['status_codes']}")
        print(f"  503 count        : {result['five_oh_three_count']}  (must be 0)")
        print(f"  500 count        : {result['five_hundred_count']}  (must be 0)")
        print(
            f"  X-Request-ID hits: {result['request_id_header_count']}"
            f"  (must equal attempted)"
        )
        print(f"  project_ids ok   : {result['project_ids_created']}")
        if result["sample_errors"]:
            print("  first 5 errors   :")
            for err in result["sample_errors"]:
                print(f"    - {err}")
        print(f"  RESULT           : {'PASS' if result['passed'] else 'FAIL'}")

    return 0 if result["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
